# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nvidia-dind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nvidia-dind
  template:
    metadata:
      labels:
        app: nvidia-dind
    spec:
      hostname: nvidia-dind
      containers:
      - name: nvidia-dind
        image: ghcr.io/ehfd/nvidia-dind:latest
        stdin: true
        tty: true
        env:
          # if set NVIDIA_VISIBLE_DEVICES and NVIDIA_DRIVER_CAPABILITIES , you can not set gpu resources limits
          - name: NVIDIA_VISIBLE_DEVICES
            value: all
          - name: NVIDIA_DRIVER_CAPABILITIES
            value: all
        securityContext:
          privileged: true
        resources:
          limits:
            memory: 64Gi
            cpu: "16"
            nvidia.com/gpu: 1
          requests:
            memory: 100Mi
            cpu: 100m
        volumeMounts:
        - mountPath: /var/lib/docker
          name: data
      volumes:
      - name: data
        # Change to a PersistentVolumeClaim to preserve images and containers, otherwise keep this line to prevent file system error
        emptyDir: {}
